name: create pr from release to master

on:
  push:
    branches:
      - main

jobs:
  releaseToMain:
    runs-on: ubuntu-latest
    env:
      GIT_PR_RELEASE_BRANCH_PRODUCTION: main
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: git log
